

### 회원가입 (고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "2023-03-29",
  "email": "kmju1235@gmail.com",
  "name": "pumkin",
  "password": "password",
  "phone": "01012341234"
}

### 이메일 인증
GET http://localhost:8081/signup/customer/verify?email=kmju1235@gmail.com&code=9I0a2iIQ3D

### 로그인 (고객)
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "kmju1235@gmail.com",
  "password": "password"
}

### 회원 정보 조회 (고객)
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmajVaWm9GTnpjNWdNcjEwQWFObkFtK2FlaEhJL1owZHNxNEF2N0pnZzlzPSIsImp0aSI6IjFRQm15bDFHQ3F4eVVSYkdvVFFYblE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAxMTY3MTYsImV4cCI6MTY4MDIwMzExNn0.x4ghtTDEJH7ISZ6xkQabOPUgreFDT-KsUwb_iVCJdGc

### 잔액 변경 (고객)
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmajVaWm9GTnpjNWdNcjEwQWFObkFtK2FlaEhJL1owZHNxNEF2N0pnZzlzPSIsImp0aSI6IjFRQm15bDFHQ3F4eVVSYkdvVFFYblE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAxMTY3MTYsImV4cCI6MTY4MDIwMzExNn0.x4ghtTDEJH7ISZ6xkQabOPUgreFDT-KsUwb_iVCJdGc

{
  "from": "admin",
  "message": "5000원 용돈",
  "money": 5000
}

########################


### 회원가입 (셀러)
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "2023-03-29",
  "email": "kmju1235@gmail.com",
  "name": "pumkin",
  "password": "password",
  "phone": "01012341111"
}

### 이메일 인증
GET http://localhost:8081/signup/seller/verify?email=kmju1235@gmail.com&code=SBUvs8HSvB

### 로그인 (셀러)
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "kmju1235@gmail.com",
  "password": "password"
}